### ISSUE TITLE
use match() instead of grep() in formCombinedTable()

### ISSUE THREAD

**Issue by caeu** [hhabra/metabCombiner#19]
In the file `form.R`, the function `formCombinedTable()` is causing an error for us because it uses `grep()` to get the indices of matching IDs. The grep is failing because the string for regex pattern gets too big since we have thousands of IDs.

A fix would be to use match() instead, which also avoid another potential source of error -see below.  Here are my suggested changes, which seem to work, in the file `form.R`:
```
formCombinedTable <- function(object, xset, yset, xreps, yreps){
    xComb <- dplyr::slice(xset, rep(seq(1,n()), times = xreps))
    yComb <- yset[yreps,]
    samps_extras <- unlist(lapply(datasets(object), function(d)
        c(getSamples(object, d), getExtra(object,d))))
    # samps_extras <- rmbrackets(paste(samps_extras, collapse = "|"))            # removed
    # x_sa_ext <- setdiff(grep(samps_extras, rmbrackets(names(xComb))),seq(1,5)) # removed
    x_sa_ext <- na.omit(match(samps_extras, names(xComb)))                       # added
    x_sa_ext <- x_sa_ext[x_sa_ext > 5]                                           # added
    # y_sa_ext <- setdiff(grep(samps_extras, rmbrackets(names(yComb))),seq(1,5)) # removed
    y_sa_ext <- na.omit(match(samps_extras, names(yComb)))                       # added
    y_sa_ext <- y_sa_ext[y_sa_ext > 5]                                           # added
    cTable <- data.frame(idx = xComb[["id"]], idy = yComb[["id"]],
                    mzx = round(xComb[["mz"]],5), mzy = round(yComb[["mz"]],5),
                    rtx = round(xComb[["rt"]],4), rty = round(yComb[["rt"]],4),
                    rtProj = numeric(nrow(xComb)),
                    Qx = round(xComb[["Q"]],4), Qy = round(yComb[["Q"]],4),
                    group = xComb[["group"]],
                    score = rep(1, nrow(xComb)),
                    rankX = as.integer(1), rankY = as.integer(1),
                    adductx = xComb[["adduct"]], adducty = yComb[["adduct"]],
                    xComb[,sort(x_sa_ext)], yComb[,sort(y_sa_ext)],
                    stringsAsFactors = FALSE, check.names = FALSE)
    consec <- lapply(rle(cTable[["group"]])[["lengths"]], function(l) seq(1,l))
    consec <- unlist(consec)
    rowID <- sprintf("%s.%s", cTable[["group"]], consec)
    cTable <- cbind.data.frame(rowID = rowID, cTable)

    return(cTable)
}
```

The grep() approach will produce unintended matches in cases of varying length IDs where some IDs are substrings of others, for example, if the search pattern has the ID `123` then it will match `1230` `1123` and `1231` etc.

Caesar

**Comment by hhabra** [comment]
Hi there! Could you please provide the .RDS files for your metabData/ metabCombiner object inputs? They could be useful as test cases for the package. Thanks!

**Comment by hhabra** [comment]
I've updated the function with your suggested change (plus a slight modification to account for potential duplicate sample or extra column names).

**Comment by caeu** [comment]
Thanks for the fix!
One small thing about the exclusion col name indices `< 6`, which makes sense, those aren't IDs. For the same reason, you might consider excluding col 6 `"Q"` and the last column name `"group"` too. Here is my suggestion. 
```
x_samps_extras <- x_samps_extras[x_samps_extras > 7 | x_simps_extras == ncol(xComb)]
y_samps_extras <- y_samps_extras[y_samps_extras > 7 | y_samps_extras == ncol(yComb)]
```
Can't share our test data because it's sensitive.

Feel free to close this issue.
